In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%config InlineBackend.figure_format = 'svg'
#%config InlineBackend.figure_format = 'pdf'

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import tensorflow as tf

In [ ]:
# font options
font = {
    #'family' : 'normal',
    #'weight' : 'bold',
    'size'   : 18
}

plt.rc('font', **font)
plt.rc('lines', linewidth=2)
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

In [2]:
a = np.reshape(np.arange(6), [3, 2])
b = np.reshape(np.arange(6, 12), [3, 2])

In [3]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [9]:
a1 = a[:, np.newaxis]
a1

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [15]:
b1 = b[:, np.newaxis]
b1

array([[[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

In [16]:
np.concatenate((a1, b1), axis=2)

array([[[ 0,  1,  6,  7]],

       [[ 2,  3,  8,  9]],

       [[ 4,  5, 10, 11]]])

## New axis as the first index

In [17]:
a0 = a[np.newaxis, :]
a0

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [18]:
b0 = b[np.newaxis, :]
b0

array([[[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [19]:
ab0 = np.concatenate((a0, b0), axis=0)
ab0

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [21]:
T = np.transpose(ab0, (1, 2, 0))
T

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [24]:
T.reshape(3, -1)

array([[ 0,  6,  1,  7],
       [ 2,  8,  3,  9],
       [ 4, 10,  5, 11]])

## Sum a tensor along one dim

In [25]:
A = np.arange(24).reshape(4, 3, 2)

In [27]:
np.sum(A, 1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])